# Generated by Django 4.1.5 on 2023-01-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=250)),
                ('lName', models.CharField(max_length=250)),
                ('usr_contact_num', models.IntegerField()),
                ('usr_gender', models.CharField(max_length=250)),
                ('usr_city', models.CharField(max_length=250)),
                ('usr_barangay', models.CharField(max_length=250)),
                ('usr_street', models.CharField(max_length=250)),
                ('usr_zipcode', models.CharField(max_length=150)),
                ('usr_province', models.CharField(max_length=250)),
                ('usr_username', models.CharField(max_length=250)),
                ('usr_password', models.CharField(max_length=250)),
                ('usr_email', models.CharField(max_length=250)),
            ],
        ),
    ]
